version: '3.8'

services: 
  mysqldb:
    image: mysql
    restart: always
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nazwabazy
    ports:
      - 3306:3306
    volumes: 
      - ./db-config/mysql.cnf:/etc/mysql/my.cnf
      # - db-data:/var/lib/mysql
      # - ./db/backup/files/:/data_backup/data
    
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-mysql-app
    networks:
      - backend
    depends_on:
      - mysqldb
    ports:
      - 3000:3000
    stdin_open: true
    tty: true


networks:
  backend: